name: 9HITS
on:
    # push:
    workflow_dispatch:
    schedule:
    #   - cron: '*/15 * * * *'
      - cron: '0 0 * * *'
    # schedule:
    #     - cron: '1/2 * * * *'
    # schedule:
    #     - cron: '0 0 0/24 * * *'
        

env:
    USER_ID_GRASS: ${{ secrets.USER_ID_GRASS }}
    NODEPAY_TOKEN: ${{ secrets.NODEPAY_TOKEN }}

# apt update

jobs:  
    job_nodepay2:
        runs-on: ubuntu-latest
        timeout-minutes: 1440
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: update
              run: |
                DIR=$(pwd)
                wget http://dl.9hits.com/3.0.4/9hitsv3-linux64.tar.bz2
                tar -xvf 9hitsv3-linux64.tar.bz2
                cd 9hitsv3-linux64
                HITS_DIR=$(pwd)
                cp -rf $DIR/9hits/config $HITS_DIR
                ./9hits

    # job_nodepay1:
    #     runs-on: ubuntu-latest
    #     timeout-minutes: 1440
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: Nodepay-install
    #           run: |
    #             cd nodepay
    #             python -m venv venv
    #             source venv/bin/activate
    #             pip install -r requirements.txt
    #         - name: Nodepay-run
    #           run: |
    #             cd nodepay
    #             source venv/bin/activate
    #             timeout 2m python noproxy.py
    #           shell: bash
    # job_nodepay:
    #     runs-on: ubuntu-latest
    #     timeout-minutes: 1440
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: Nodepay-install
    #           run: |
    #             cd nodepay
    #             python -m venv venv
    #             source venv/bin/activate
    #             pip install -r requirements.txt
    #         - name: Nodepay-run
    #           run: |
    #             cd nodepay
    #             source venv/bin/activate
    #             timeout 2m python noproxy.py
    #           shell: bash                
    # job_grass:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: Grass-install
    #           run: |
    #             cd grass
    #             python -m venv venv
    #             source venv/bin/activate
    #             pip install -r requirements.txt
    #         - name: Grass-run
    #           run: |
    #             cd grass
    #             source venv/bin/activate
    #             python grass.py